edit_uri: ""
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search:
      indexing: titles
      min_search_length: 2
      prebuild_index: true
      separator: '[\s\-\.]+'
  - minify:
      minify_html: true
repo_name: EmbarkStudios/jsonnet-libs
repo_url: https://github.com/EmbarkStudios/jsonnet-libs
site_name: jsonnet libraries
site_url: https://EmbarkStudios.github.io/jsonnet-libs
theme:
  name: material
  palette:
    - accent: indigo
      media: '(prefers-color-scheme: light)'
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - accent: red
      media: '(prefers-color-scheme: dark)'
      primary: red
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
